using System.Collections.Generic;
using System.Text;
using AStergio.OmniCard.Runtime.Cards.Data;
using FateDeck.Runtime.Core;

namespace FateDeck.Runtime.Simulation
{
    /// <summary>Aggregate statistics of many simulated runs for one hero.</summary>
    public sealed class HeroReport
    {
        public string HeroName;
        public int Runs;
        public int Victories;
        public int Stalls;
        public int[] DeathsByStep = new int[0];
        public double AverageFlips;
        public double AverageDebtFlips;
        public double AverageReshuffles;
        public double AverageGoldOfWinners;
        public double AverageEscrowAtEnd;
        public double AverageDeckAtEnd;
        public readonly Dictionary<string, int> FatalActions = new Dictionary<string, int>();

        public double WinRate => Runs > 0 ? (double)Victories / Runs : 0;

        public double AverageDeathStep
        {
            get
            {
                int deaths = 0;
                int total = 0;
                for (int step = 0; step < DeathsByStep.Length; step++)
                {
                    deaths += DeathsByStep[step];
                    total += DeathsByStep[step] * step;
                }

                return deaths > 0 ? (double)total / deaths : 0;
            }
        }
    }

    /// <summary>
    /// The balance lab: plays the <see cref="AutoPlayer"/> across seeded runs and aggregates
    /// the numbers the tuning pass cares about - win rates, death-step distributions, Debt
    /// pressure and gold curves. Same seed set per hero, so heroes compare fairly.
    /// </summary>
    public static class RunSimulator
    {
        public static HeroReport Simulate(FateContentCatalog catalog, CardDefinition hero,
            int runs, int firstSeed = 101)
        {
            var player = new AutoPlayer(catalog);
            var report = new HeroReport
            {
                HeroName = hero != null ? hero.name : "(default)",
                Runs = runs,
                DeathsByStep = new int[catalog.Rules.TrackSteps + 2]
            };

            double gold = 0;
            for (int i = 0; i < runs; i++)
            {
                RunResult result = player.Play(hero, firstSeed + i);
                report.AverageFlips += result.Flips;
                report.AverageDebtFlips += result.DebtFlips;
                report.AverageReshuffles += result.Reshuffles;
                report.AverageEscrowAtEnd += result.EscrowAtEnd;
                report.AverageDeckAtEnd += result.DeckAtEnd;

                if (result.Victory)
                {
                    report.Victories++;
                    gold += result.FinalGold;
                }
                else if (result.Stalled)
                {
                    report.Stalls++;
                }
                else
                {
                    int step = result.DeathStep;
                    if (step < 0)
                    {
                        step = 0;
                    }

                    if (step >= report.DeathsByStep.Length)
                    {
                        step = report.DeathsByStep.Length - 1;
                    }

                    report.DeathsByStep[step]++;
                    string cause = string.IsNullOrEmpty(result.FatalAction) ? "(unknown)" : result.FatalAction;
                    report.FatalActions.TryGetValue(cause, out int seen);
                    report.FatalActions[cause] = seen + 1;
                }
            }

            if (runs > 0)
            {
                report.AverageFlips /= runs;
                report.AverageDebtFlips /= runs;
                report.AverageReshuffles /= runs;
                report.AverageEscrowAtEnd /= runs;
                report.AverageDeckAtEnd /= runs;
            }

            if (report.Victories > 0)
            {
                report.AverageGoldOfWinners = gold / report.Victories;
            }

            return report;
        }

        public static List<HeroReport> SimulateAll(FateContentCatalog catalog, int runsPerHero,
            int firstSeed = 101)
        {
            var reports = new List<HeroReport>();
            foreach (CardDefinition hero in catalog.Heroes)
            {
                reports.Add(Simulate(catalog, hero, runsPerHero, firstSeed));
            }

            return reports;
        }

        /// <summary>Renders reports as the BalanceReport.md the tuning pass reads.</summary>
        public static string ToMarkdown(IReadOnlyList<HeroReport> reports, FateRulesDefinition rules,
            string note = null)
        {
            var text = new StringBuilder();
            text.AppendLine("# Fate Deck - Balance Report");
            text.AppendLine();
            text.AppendLine("Auto-generated by Tools > Fate Deck > Run Balance Simulation. The bot is a");
            text.AppendLine("deliberately-simple baseline (no charms, no scry ordering), so a human should");
            text.AppendLine("beat these win rates comfortably; treat the numbers as a floor, not a target.");
            if (!string.IsNullOrEmpty(note))
            {
                text.AppendLine();
                text.AppendLine(note);
            }

            text.AppendLine();
            text.AppendLine("| Hero | Runs | Win rate | Avg death step | Avg flips | Debt flips | Reshuffles | Escrow at end | Deck at end | Gold of winners |");
            text.AppendLine("| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |");
            foreach (HeroReport report in reports)
            {
                text.AppendLine($"| {report.HeroName} | {report.Runs} | {report.WinRate:P0} "
                    + $"| {report.AverageDeathStep:0.0} | {report.AverageFlips:0.0} "
                    + $"| {report.AverageDebtFlips:0.0} | {report.AverageReshuffles:0.0} "
                    + $"| {report.AverageEscrowAtEnd:0.0} | {report.AverageDeckAtEnd:0.0} "
                    + $"| {report.AverageGoldOfWinners:0.#}g |");
            }

            foreach (HeroReport report in reports)
            {
                text.AppendLine();
                text.AppendLine($"## {report.HeroName}");
                text.AppendLine();
                if (report.Stalls > 0)
                {
                    text.AppendLine($"Stalled runs (bot hit its iteration cap): {report.Stalls}.");
                    text.AppendLine();
                }

                text.AppendLine("Deaths by step:");
                text.AppendLine();
                text.AppendLine("```");
                int most = 1;
                foreach (int count in report.DeathsByStep)
                {
                    if (count > most)
                    {
                        most = count;
                    }
                }

                for (int step = 1; step < report.DeathsByStep.Length; step++)
                {
                    int count = report.DeathsByStep[step];
                    int width = count * 40 / most;
                    string label = step == rules.TrackSteps ? "boss" : $"step {step,2}";
                    text.AppendLine($"{label} | {new string('#', width)} {count}");
                }

                text.AppendLine("```");
                if (report.FatalActions.Count > 0)
                {
                    text.AppendLine();
                    text.AppendLine("What killed the bot most:");
                    text.AppendLine();
                    var causes = new List<KeyValuePair<string, int>>(report.FatalActions);
                    causes.Sort((a, b) => b.Value.CompareTo(a.Value));
                    int shown = 0;
                    foreach (KeyValuePair<string, int> cause in causes)
                    {
                        text.AppendLine($"- {cause.Key}: {cause.Value}");
                        if (++shown >= 6)
                        {
                            break;
                        }
                    }
                }
            }

            return text.ToString();
        }
    }
}
